name: ngIRCd CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'COPYING'
      - 'ChangeLog'
      - 'NEWS'
      - 'contrib/**'
      - 'doc/**'
      - 'man/**'
      - '**.md'
      - '**.txt'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'COPYING'
      - 'ChangeLog'
      - 'NEWS'
      - 'contrib/**'
      - 'doc/**'
      - 'man/**'
      - '**.md'
      - '**.txt'

jobs:
  build_and_distcheck:

    name: Configure ngIRCd sources and run make targets "all" and "distcheck"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4
    - uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: >
	  autoconf
	  automake
	  build-essential
	  expect
	  libident-dev
	  libpam0g-dev
	  libssl-dev
	  libwrap0-dev
	  pkg-config
	  telnet
	  zlib1g-dev
        version: 1.0
    - name: Generate build system files
      run: ./autogen.sh
    - name: Configure the build system
      run: ./configure --enable-ipv6 --with-iconv --with-ident --with-openssl --with-pam --with-tcp-wrappers --with-zlib
    - name: Build everything
      run: make all
    - name: Create distribution archive and run tests
      run: make distcheck
